name: Termius SSH Session

on:
  workflow_dispatch:

jobs:
  ssh-session:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH & Pinggy Tunnel
        run: |
          # Set password for runner user
          echo "runner:123456" | sudo chpasswd
          
          # Enable SSH service
          sudo systemctl start ssh
          
          # Start Pinggy TCP tunnel (No Token / No Card required)
          ssh -p 443 -R0:localhost:22 qr@a.pinggy.io
